#ifdef USE_DERIVED_OBJECTS
#endif

#ifdef USE_HELP_CONTEXTS
#endif

#ifdef USE_WINDOW_DICTIONARY
const ZIL_UINT16 DCT_INPUT                        = 0x0004;
const ZIL_UINT16 DCT_DEFINITION                   = 0x0005;
const ZIL_UINT16 DCT_ANTONYM                      = 0x0006;
const ZIL_UINT16 DCT_SYNONYM                      = 0x0007;
const ZIL_UINT16 FIELD_0                          = 0x0001;
const ZIL_UINT16 DCT_LOOKUP_BUTTON                = 0x000A;
const ZIL_UINT16 DCT_SAVE_BUTTON                  = 0x000B;
const ZIL_UINT16 DCT_DELETE_BUTTON                = 0x000C;
const ZIL_UINT16 FIELD_25                         = 0x0003;
const ZIL_UINT16 FIELD_26                         = 0x0008;
const ZIL_UINT16 FIELD_27                         = 0x0009;
#endif

