//  WINDOW.HPP (WINDOW) - Getting/Setting data in fields of a window.
//  COPYRIGHT (C) 1990-1995.  All Rights Reserved.
//  Zinc Software Incorporated.  Pleasant Grove, Utah  USA
//  May be freely copied, used and distributed.

#if defined(USE_EDIT_WINDOW)
const ZIL_NUMBERID NAME                             = 0x0002;
const ZIL_NUMBERID ADDRESS                          = 0x0003;
const ZIL_NUMBERID CITY                             = 0x0004;
const ZIL_NUMBERID PHONE                            = 0x0005;
const ZIL_NUMBERID EDIT_NAME                        = 0x000A;
const ZIL_NUMBERID EDIT_ADDRESS                     = 0x000B;
const ZIL_NUMBERID EDIT_CITY                        = 0x000C;
const ZIL_NUMBERID EDIT_PHONE                       = 0x000D;
const ZIL_NUMBERID VIEW_BUTTON                      = 0x000F;
#endif

#if defined(USE_VIEW_WINDOW)
const ZIL_NUMBERID VIEW_NAME                        = 0x0001;
const ZIL_NUMBERID VIEW_CITY                        = 0x0002;
const ZIL_NUMBERID VIEW_ADDRESS                     = 0x0003;
const ZIL_NUMBERID VIEW_PHONE                       = 0x0004;
const ZIL_NUMBERID FIELD_9                          = 0x0009;
const ZIL_NUMBERID FIELD_10                         = 0x000A;
#endif

#if defined(USE_DERIVED_OBJECTS)
#endif

