#if defined(USE_WINDOW_BUTTON)
const ZIL_NUMBERID FIELD_22                         = 0x0016;
const ZIL_NUMBERID FIELD_0                          = 0x0015;
const ZIL_NUMBERID FIELD_1                          = 0x0001;
const ZIL_NUMBERID FIELD_2                          = 0x0002;
const ZIL_NUMBERID FIELD_3                          = 0x0003;
const ZIL_NUMBERID FIELD_4                          = 0x0004;
const ZIL_NUMBERID FIELD_5                          = 0x0005;
const ZIL_NUMBERID FIELD_6                          = 0x0006;
const ZIL_NUMBERID FIELD_7                          = 0x0007;
const ZIL_NUMBERID FIELD_8                          = 0x0008;
const ZIL_NUMBERID FIELD_9                          = 0x0009;
const ZIL_NUMBERID FIELD_10                         = 0x000A;
const ZIL_NUMBERID FIELD_11                         = 0x000B;
const ZIL_NUMBERID FIELD_12                         = 0x000C;
const ZIL_NUMBERID FIELD_13                         = 0x000D;
const ZIL_NUMBERID FIELD_14                         = 0x000E;
const ZIL_NUMBERID FIELD_15                         = 0x000F;
const ZIL_NUMBERID FIELD_16                         = 0x0010;
const ZIL_NUMBERID FIELD_17                         = 0x0011;
const ZIL_NUMBERID FIELD_18                         = 0x0012;
const ZIL_NUMBERID FIELD_19                         = 0x0013;
const ZIL_NUMBERID FIELD_20                         = 0x0014;
#endif

#if defined(USE_WINDOW_COMBO_BOX)
const ZIL_NUMBERID FIELD_0                          = 0x001C;
const ZIL_NUMBERID FIELD_21                         = 0x0015;
const ZIL_NUMBERID FIELD_24                         = 0x0018;
const ZIL_NUMBERID FIELD_25                         = 0x0019;
const ZIL_NUMBERID FIELD_26                         = 0x001A;
const ZIL_NUMBERID FIELD_27                         = 0x001B;
const ZIL_NUMBERID FIELD_20                         = 0x0014;
const ZIL_NUMBERID FIELD_1                          = 0x0001;
const ZIL_NUMBERID FIELD_4                          = 0x0004;
const ZIL_NUMBERID FIELD_9                          = 0x0009;
const ZIL_NUMBERID FIELD_10                         = 0x000A;
const ZIL_NUMBERID FIELD_11                         = 0x000B;
const ZIL_NUMBERID FIELD_12                         = 0x000C;
const ZIL_NUMBERID FIELD_13                         = 0x000D;
const ZIL_NUMBERID FIELD_14                         = 0x000E;
const ZIL_NUMBERID FIELD_15                         = 0x000F;
const ZIL_NUMBERID FIELD_16                         = 0x0010;
const ZIL_NUMBERID FIELD_17                         = 0x0011;
const ZIL_NUMBERID FIELD_18                         = 0x0012;
const ZIL_NUMBERID FIELD_19                         = 0x0013;
#endif

#if defined(USE_WINDOW_GENERIC)
#endif

#if defined(USE_WINDOW_ICON)
const ZIL_NUMBERID FIELD_0                          = 0x0008;
const ZIL_NUMBERID FIELD_1                          = 0x0001;
const ZIL_NUMBERID FIELD_2                          = 0x0002;
const ZIL_NUMBERID FIELD_3                          = 0x0003;
const ZIL_NUMBERID FIELD_4                          = 0x0004;
const ZIL_NUMBERID FIELD_5                          = 0x0005;
const ZIL_NUMBERID FIELD_6                          = 0x0006;
const ZIL_NUMBERID FIELD_7                          = 0x0007;
#endif

#if defined(USE_WINDOW_LIST)
const ZIL_NUMBERID FIELD_0                          = 0x0034;
const ZIL_NUMBERID FIELD_1                          = 0x0001;
const ZIL_NUMBERID FIELD_6                          = 0x0006;
const ZIL_NUMBERID FIELD_7                          = 0x0007;
const ZIL_NUMBERID FIELD_8                          = 0x0008;
const ZIL_NUMBERID FIELD_9                          = 0x0009;
const ZIL_NUMBERID FIELD_10                         = 0x000A;
const ZIL_NUMBERID FIELD_11                         = 0x000B;
const ZIL_NUMBERID FIELD_12                         = 0x000C;
const ZIL_NUMBERID FIELD_13                         = 0x000D;
const ZIL_NUMBERID FIELD_14                         = 0x000E;
const ZIL_NUMBERID FIELD_15                         = 0x000F;
const ZIL_NUMBERID FIELD_16                         = 0x0010;
const ZIL_NUMBERID FIELD_17                         = 0x0011;
const ZIL_NUMBERID FIELD_18                         = 0x0012;
const ZIL_NUMBERID FIELD_19                         = 0x0013;
const ZIL_NUMBERID FIELD_20                         = 0x0014;
const ZIL_NUMBERID FIELD_21                         = 0x0015;
const ZIL_NUMBERID FIELD_22                         = 0x0016;
const ZIL_NUMBERID FIELD_23                         = 0x0017;
const ZIL_NUMBERID FIELD_24                         = 0x0018;
const ZIL_NUMBERID FIELD_25                         = 0x0019;
const ZIL_NUMBERID FIELD_26                         = 0x001A;
const ZIL_NUMBERID FIELD_27                         = 0x001B;
const ZIL_NUMBERID FIELD_32                         = 0x0020;
const ZIL_NUMBERID FIELD_33                         = 0x0021;
const ZIL_NUMBERID FIELD_34                         = 0x0022;
const ZIL_NUMBERID FIELD_35                         = 0x0023;
const ZIL_NUMBERID FIELD_36                         = 0x0024;
const ZIL_NUMBERID FIELD_37                         = 0x0025;
const ZIL_NUMBERID FIELD_38                         = 0x0026;
const ZIL_NUMBERID FIELD_39                         = 0x0027;
const ZIL_NUMBERID FIELD_40                         = 0x0028;
const ZIL_NUMBERID FIELD_41                         = 0x0029;
const ZIL_NUMBERID FIELD_42                         = 0x002A;
const ZIL_NUMBERID FIELD_43                         = 0x002B;
const ZIL_NUMBERID FIELD_44                         = 0x002C;
const ZIL_NUMBERID FIELD_45                         = 0x002D;
const ZIL_NUMBERID FIELD_46                         = 0x002E;
const ZIL_NUMBERID FIELD_47                         = 0x002F;
const ZIL_NUMBERID FIELD_48                         = 0x0030;
const ZIL_NUMBERID FIELD_49                         = 0x0031;
const ZIL_NUMBERID FIELD_50                         = 0x0032;
const ZIL_NUMBERID FIELD_51                         = 0x0033;
#endif

#if defined(USE_WINDOW_MENU)
const ZIL_NUMBERID FIELD_0                          = 0x0005;
const ZIL_NUMBERID FIELD_1                          = 0x0001;
const ZIL_NUMBERID FIELD_6                          = 0x0006;
const ZIL_NUMBERID FIELD_7                          = 0x0007;
const ZIL_NUMBERID FIELD_8                          = 0x0008;
const ZIL_NUMBERID FIELD_9                          = 0x0009;
const ZIL_NUMBERID FIELD_10                         = 0x000A;
const ZIL_NUMBERID FIELD_11                         = 0x000B;
const ZIL_NUMBERID FIELD_12                         = 0x000C;
const ZIL_NUMBERID FIELD_13                         = 0x000D;
const ZIL_NUMBERID FIELD_14                         = 0x000E;
const ZIL_NUMBERID FIELD_15                         = 0x000F;
const ZIL_NUMBERID FIELD_16                         = 0x0010;
const ZIL_NUMBERID FIELD_17                         = 0x0011;
const ZIL_NUMBERID FIELD_2                          = 0x0002;
const ZIL_NUMBERID FIELD_18                         = 0x0012;
const ZIL_NUMBERID FIELD_19                         = 0x0013;
const ZIL_NUMBERID FIELD_20                         = 0x0014;
const ZIL_NUMBERID FIELD_21                         = 0x0015;
const ZIL_NUMBERID FIELD_3                          = 0x0003;
const ZIL_NUMBERID FIELD_22                         = 0x0016;
const ZIL_NUMBERID FIELD_23                         = 0x0017;
const ZIL_NUMBERID FIELD_24                         = 0x0018;
const ZIL_NUMBERID FIELD_25                         = 0x0019;
const ZIL_NUMBERID FIELD_4                          = 0x0004;
#endif

#if defined(USE_WINDOW_NUMBER)
const ZIL_NUMBERID FIELD_0                          = 0x000D;
const ZIL_NUMBERID FIELD_1                          = 0x0001;
const ZIL_NUMBERID FIELD_2                          = 0x0002;
const ZIL_NUMBERID FIELD_3                          = 0x0003;
const ZIL_NUMBERID FIELD_4                          = 0x0004;
const ZIL_NUMBERID FIELD_5                          = 0x0005;
const ZIL_NUMBERID FIELD_6                          = 0x0006;
const ZIL_NUMBERID FIELD_7                          = 0x0007;
const ZIL_NUMBERID FIELD_8                          = 0x0008;
const ZIL_NUMBERID FIELD_9                          = 0x0009;
const ZIL_NUMBERID FIELD_10                         = 0x000A;
const ZIL_NUMBERID FIELD_11                         = 0x000B;
const ZIL_NUMBERID FIELD_12                         = 0x000C;
#endif

#if defined(USE_WINDOW_STRING)
const ZIL_NUMBERID FIELD_15                         = 0x000F;
const ZIL_NUMBERID FIELD_0                          = 0x000B;
const ZIL_NUMBERID FIELD_1                          = 0x0001;
const ZIL_NUMBERID FIELD_2                          = 0x0002;
const ZIL_NUMBERID FIELD_3                          = 0x0003;
const ZIL_NUMBERID FIELD_4                          = 0x0004;
const ZIL_NUMBERID FIELD_5                          = 0x0005;
const ZIL_NUMBERID FIELD_6                          = 0x0006;
const ZIL_NUMBERID FIELD_7                          = 0x0007;
const ZIL_NUMBERID FIELD_12                         = 0x000C;
const ZIL_NUMBERID FIELD_13                         = 0x000D;
const ZIL_NUMBERID FIELD_14                         = 0x000E;
#endif

#if defined(USE_WINDOW_TEXT)
const ZIL_NUMBERID FIELD_0                          = 0x000A;
const ZIL_NUMBERID FIELD_9                          = 0x0009;
#endif

#if defined(USE_WINDOW_TIME)
const ZIL_NUMBERID FIELD_0                          = 0x000B;
const ZIL_NUMBERID FIELD_1                          = 0x0001;
const ZIL_NUMBERID FIELD_2                          = 0x0002;
const ZIL_NUMBERID FIELD_3                          = 0x0003;
const ZIL_NUMBERID FIELD_4                          = 0x0004;
const ZIL_NUMBERID FIELD_5                          = 0x0005;
const ZIL_NUMBERID FIELD_6                          = 0x0006;
const ZIL_NUMBERID FIELD_7                          = 0x0007;
const ZIL_NUMBERID FIELD_8                          = 0x0008;
const ZIL_NUMBERID FIELD_9                          = 0x0009;
const ZIL_NUMBERID FIELD_10                         = 0x000A;
#endif

#if defined(USE_WINDOW_TOOL_BAR)
const ZIL_NUMBERID FIELD_0                          = 0x000E;
const ZIL_NUMBERID FIELD_1                          = 0x0001;
const ZIL_NUMBERID FIELD_2                          = 0x0002;
const ZIL_NUMBERID FIELD_3                          = 0x0003;
const ZIL_NUMBERID FIELD_4                          = 0x0004;
const ZIL_NUMBERID FIELD_5                          = 0x0005;
const ZIL_NUMBERID FIELD_6                          = 0x0006;
const ZIL_NUMBERID FIELD_9                          = 0x0009;
const ZIL_NUMBERID FIELD_10                         = 0x000A;
const ZIL_NUMBERID FIELD_11                         = 0x000B;
const ZIL_NUMBERID FIELD_12                         = 0x000C;
const ZIL_NUMBERID FIELD_13                         = 0x000D;
#endif

#if defined(USE_HELP_CONTEXTS)
const UI_HELP_CONTEXT HELP_COMMANDS                 = 0x001A; // Zinc Application commands...
const UI_HELP_CONTEXT HELP_GENERAL                  = 0x001C; // Zinc Application
const UI_HELP_CONTEXT HELP_HELP                     = 0x001E; // Using help...
const UI_HELP_CONTEXT HELP_KEYBOARD_CURSES          = 0x0020; // Keyboard movement... (Curses)
const UI_HELP_CONTEXT HELP_KEYBOARD_MACINTOSH       = 0x0022; // Keyboard movement... (Macintosh)
const UI_HELP_CONTEXT HELP_KEYBOARD_MOTIF           = 0x0024; // Keyboard movement... (Motif)
const UI_HELP_CONTEXT HELP_KEYBOARD_MSDOS           = 0x0026; // Keyboard movement... (DOS)
const UI_HELP_CONTEXT HELP_KEYBOARD_MSWINDOWS       = 0x0028; // Keyboard movement... (Windows)
const UI_HELP_CONTEXT HELP_KEYBOARD_OS2             = 0x002A; // Keyboard movement... (OS/2)
const UI_HELP_CONTEXT HELP_MOUSE                    = 0x002C; // Mouse movement...
const UI_HELP_CONTEXT HELP_OBJECTS                  = 0x002E; // Objects...
const UI_HELP_CONTEXT HELP_PROCEDURES               = 0x0030; // Zinc Application procedures...
#endif

#if defined(USE_WINDOW_DATE)
const ZIL_NUMBERID FIELD_22                         = 0x0016;
const ZIL_NUMBERID FIELD_0                          = 0x000D;
const ZIL_NUMBERID FIELD_1                          = 0x0001;
const ZIL_NUMBERID FIELD_2                          = 0x0002;
const ZIL_NUMBERID FIELD_3                          = 0x0003;
const ZIL_NUMBERID FIELD_4                          = 0x0004;
const ZIL_NUMBERID FIELD_5                          = 0x0005;
const ZIL_NUMBERID FIELD_6                          = 0x0006;
const ZIL_NUMBERID FIELD_7                          = 0x0007;
const ZIL_NUMBERID FIELD_8                          = 0x0008;
const ZIL_NUMBERID FIELD_9                          = 0x0009;
const ZIL_NUMBERID FIELD_10                         = 0x000A;
const ZIL_NUMBERID FIELD_11                         = 0x000B;
const ZIL_NUMBERID FIELD_12                         = 0x000C;
#endif

#if defined(USE_DERIVED_OBJECTS)
#endif

