#if defined(USE_HELP_CONTEXTS)
#endif

#if defined(USE_WINDOW)
const ZIL_NUMBERID NOTEBOOK                         = 0x0001;
const ZIL_NUMBERID FIELD_4096                       = 0x1000;
const ZIL_NUMBERID FIELD_4097                       = 0x1001;
const ZIL_NUMBERID FIELD_4098                       = 0x1002;
const ZIL_NUMBERID PAGE_1                           = 0x0001;
const ZIL_NUMBERID FIELD_7                          = 0x0007;
const ZIL_NUMBERID FIELD_8                          = 0x0008;
const ZIL_NUMBERID PAGE_2                           = 0x0003;
const ZIL_NUMBERID FIELD_9                          = 0x0009;
const ZIL_NUMBERID PAGE_3                           = 0x0005;
const ZIL_NUMBERID FIELD_4096                       = 0x1000;
const ZIL_NUMBERID FIELD_4097                       = 0x1001;
const ZIL_NUMBERID FIELD_4100                       = 0x1004;
const ZIL_NUMBERID FIELD_4101                       = 0x1005;
const ZIL_NUMBERID FIELD_4102                       = 0x1006;
#endif

#if defined(USE_DERIVED_OBJECTS)
#endif

