//  POSTWN.HPP (POSTWN) - Loading and storing a persistant window.
//  COPYRIGHT (C) 1990-1995.  All Rights Reserved.
//  Zinc Software Incorporated.  Pleasant Grove, Utah  USA
//  May be freely copied, used and distributed.

#ifdef USE_PERSONAL_DATA
const ZIL_NUMBERID FIELD_1                          = 0x0001;
const ZIL_NUMBERID NAME_FIELD                       = 0x0002;
const ZIL_NUMBERID NAME_PROMPT                      = 0x0003;
const ZIL_NUMBERID TITLE_PROMPT                     = 0x0004;
const ZIL_NUMBERID COMPANY_PROMPT                   = 0x0005;
const ZIL_NUMBERID SALARY_PROMPT                    = 0x0006;
const ZIL_NUMBERID TITLE_FIELD                      = 0x0008;
const ZIL_NUMBERID COMPANY_FIELD                    = 0x0009;
const ZIL_NUMBERID SALARY_FIELD                     = 0x000A;
#endif
#ifdef USE_DERIVED_OBJECTS
#endif
