#ifdef USE_REPORT_WINDOW
const ZIL_NUMBERID FIELD_2                          = 0x0002;
const ZIL_NUMBERID FIELD_3                          = 0x0003;
const ZIL_NUMBERID FIELD_4                          = 0x0004;
const ZIL_NUMBERID FIELD_5                          = 0x0005;
const ZIL_NUMBERID FIELD_6                          = 0x0006;
const ZIL_NUMBERID AMOUNT_FIELD                     = 0x0007;
const ZIL_NUMBERID CONVERSIONS                      = 0x0013;
const ZIL_NUMBERID FIELD_22                         = 0x0016;
const ZIL_NUMBERID FIELD_23                         = 0x0017;
const ZIL_NUMBERID FIELD_24                         = 0x0018;
const ZIL_NUMBERID FIELD_25                         = 0x0019;
#endif

#ifdef USE_DERIVED_OBJECTS
#endif

