#if defined(USE_HELP_CONTEXTS)
const UI_HELP_CONTEXT HELP_ABOUT                    = 0x0001; // About...
const UI_HELP_CONTEXT HELP_ABOUT_MOVIE              = 0x0002; // About Movie Catalog System
const UI_HELP_CONTEXT HELP_GENERAL                  = 0x0003; // General Help
const UI_HELP_CONTEXT HELP_MOVIE_FILE               = 0x0005; // File Options
const UI_HELP_CONTEXT HELP_MOVIE_INFORMATION        = 0x0006; // Movie Information Window
const UI_HELP_CONTEXT HELP_MOVIE_SELECTION          = 0x0007; // Movie Selection Window
const UI_HELP_CONTEXT HELP_MOVIE                    = 0x0004; // Movie Options
#endif

#if defined(USE_EXIT_APPLICATION)
const ZIL_NUMBERID FIELD_1                          = 0x0001;
const ZIL_NUMBERID FIELD_2                          = 0x0002;
const ZIL_NUMBERID FIELD_3                          = 0x0003;
const ZIL_NUMBERID FIELD_4                          = 0x0004;
#endif

#if defined(USE_MOVIE_CONTROL)
const ZIL_NUMBERID PULL_DOWN_MENU                   = 0x0002;
const ZIL_NUMBERID FILE_OPTION                      = 0x0003;
const ZIL_NUMBERID FIELD_30                         = 0x001E;
const ZIL_NUMBERID ABOUT_OPTION                     = 0x0009;
const ZIL_NUMBERID FILE_SEP1                        = 0x000A;
const ZIL_NUMBERID EXIT_OPTION                      = 0x0005;
const ZIL_NUMBERID MOVIE_OPTION                     = 0x0004;
const ZIL_NUMBERID FIELD_31                         = 0x001F;
const ZIL_NUMBERID CREATE_OPTION                    = 0x0013;
const ZIL_NUMBERID DELETE_OPTION                    = 0x0015;
const ZIL_NUMBERID LOAD_OPTION                      = 0x0006;
const ZIL_NUMBERID STORE_OPTION                     = 0x0007;
const ZIL_NUMBERID HELP_OPTION                      = 0x0010;
const ZIL_NUMBERID FIELD_32                         = 0x0020;
const ZIL_NUMBERID HELP_FILE                        = 0x0016;
const ZIL_NUMBERID HELP_MOVIE                       = 0x0017;
const ZIL_NUMBERID HELP_SEP1                        = 0x0018;
const ZIL_NUMBERID HELP_MOVIE_CATALOG               = 0x0019;
const ZIL_NUMBERID FIELD_33                         = 0x0021;
const ZIL_NUMBERID FIELD_26                         = 0x001A;
const ZIL_NUMBERID STATUS_PMOVIE_TITLE              = 0x001C;
const ZIL_NUMBERID STATUS_MOVIE_TITLE               = 0x001D;
const ZIL_NUMBERID TOOL_BAR                         = 0x000B;
const ZIL_NUMBERID CREATE_BUTTON                    = 0x0012;
const ZIL_NUMBERID DELETE_BUTTON                    = 0x0014;
const ZIL_NUMBERID LOAD_BUTTON                      = 0x000D;
const ZIL_NUMBERID STORE_BUTTON                     = 0x000E;
#endif

#if defined(USE_MOVIE_INFORMATION)
const ZIL_NUMBERID INFO_PTITLE                      = 0x0004;
const ZIL_NUMBERID FLD_INFO_TITLE                   = 0x0005;
const ZIL_NUMBERID INFO_PCOPYRIGHT                  = 0x0006;
const ZIL_NUMBERID FLD_INFO_COPYRIGHT               = 0x0045;
const ZIL_NUMBERID FLD_INFO_LENGTH                  = 0x002E;
const ZIL_NUMBERID INFO_PDIRECTOR                   = 0x0007;
const ZIL_NUMBERID FLD_INFO_DIRECTOR                = 0x000D;
const ZIL_NUMBERID INFO_PLEADS                      = 0x0008;
const ZIL_NUMBERID FLD_INFO_LEADS                   = 0x000E;
const ZIL_NUMBERID INFO_PDESCRIPTION                = 0x0009;
const ZIL_NUMBERID FLD_INFO_DESCRIPTION             = 0x0010;
const ZIL_NUMBERID INFO_SAVE                        = 0x0001;
const ZIL_NUMBERID FLD_PLENGTH                      = 0x0057;
const ZIL_NUMBERID INFO_CLOSE                       = 0x0002;
const ZIL_NUMBERID INFO_HELP                        = 0x0003;
#endif

#if defined(USE_MOVIE_SELECTION)
const ZIL_NUMBERID SELECT_PTITLE                    = 0x0001;
const ZIL_NUMBERID FLD_SELECT_TITLE                 = 0x0002;
const ZIL_NUMBERID FLD_SELECT_SELECTION             = 0x0006;
const ZIL_NUMBERID SELECT_OK                        = 0x0003;
const ZIL_NUMBERID SELECT_CANCEL                    = 0x0004;
const ZIL_NUMBERID SELECT_HELP                      = 0x0005;
#endif

#if defined(USE_MSG_TABLE)
const ZIL_NUMBERID ZMSG_STORE_ERROR                 = 0x0001;
const ZIL_NUMBERID ZMSG_LOAD_ERROR                  = 0x0002;
const ZIL_NUMBERID ZMSG_DELETE_ERROR                = 0x0003;
const ZIL_NUMBERID ZMSG_NAME_ERROR                  = 0x0004;
const ZIL_NUMBERID ZMSG_CTRL_PATH_NAME              = 0x000A;
const ZIL_NUMBERID ZMSG_CTRL_EXIT_NAME              = 0x000B;
const ZIL_NUMBERID ZMSG_SEL_PATH_NAME               = 0x0014;
const ZIL_NUMBERID ZMSG_SEL_PATH_TEXT               = 0x0015;
const ZIL_NUMBERID ZMSG_SEL_ALL_NAME                = 0x0016;
const ZIL_NUMBERID ZMSG_INFO_PATH_NAME              = 0x001E;
const ZIL_NUMBERID ZMSG_DATA_FILE                   = 0x0028;
#endif

#if defined(USE_MOVIE_SELECTION_TEXT)
const ZIL_NUMBERID SELECT_PTITLE                    = 0x0001;
const ZIL_NUMBERID FLD_SELECT_TITLE                 = 0x0002;
const ZIL_NUMBERID FLD_SELECT_SELECTION             = 0x0006;
const ZIL_NUMBERID SELECT_OK                        = 0x0003;
const ZIL_NUMBERID SELECT_CANCEL                    = 0x0004;
const ZIL_NUMBERID SELECT_HELP                      = 0x0005;
#endif

#if defined(USE_DERIVED_OBJECTS)
#endif

