#if defined(USE_MOVIE_CONTROL)
const ZIL_NUMBERID PULL_DOWN_MENU                   = 0x0001;
const ZIL_NUMBERID FILE_OPTION                      = 0x0002;
const ZIL_NUMBERID FIELD_8                          = 0x0008;
const ZIL_NUMBERID ABOUT_OPTION                     = 0x0005;
const ZIL_NUMBERID FILE_SEP1                        = 0x0006;
const ZIL_NUMBERID EXIT_OPTION                      = 0x0007;
const ZIL_NUMBERID MOVIE_OPTION                     = 0x0003;
const ZIL_NUMBERID HELP_OPTION                      = 0x0004;
#endif

#if defined(USE_DERIVED_OBJECTS)
#endif

