#if defined(USE_HELP_CONTEXTS)
const UI_HELP_CONTEXT MOVIE_INFORMATION             = 0x0001; // Movie Information
const UI_HELP_CONTEXT MOVIE_SELECTION               = 0x0002; // Movie Selection
#endif

#if defined(USE_MOVIE_CONTROL)
const ZIL_NUMBERID PULL_DOWN_MENU                   = 0x0002;
const ZIL_NUMBERID FILE_OPTION                      = 0x0003;
const ZIL_NUMBERID ABOUT_OPTION                     = 0x0009;
const ZIL_NUMBERID FILE_SEP1                        = 0x000A;
const ZIL_NUMBERID EXIT_OPTION                      = 0x0005;
const ZIL_NUMBERID MOVIE_OPTION                     = 0x0004;
const ZIL_NUMBERID CREATE_OPTION                    = 0x0013;
const ZIL_NUMBERID LOAD_OPTION                      = 0x0006;
const ZIL_NUMBERID STORE_OPTION                     = 0x0007;
const ZIL_NUMBERID DELETE_OPTION                    = 0x0015;
const ZIL_NUMBERID HELP_OPTION                      = 0x0010;
const ZIL_NUMBERID HELP_FILE                        = 0x0016;
const ZIL_NUMBERID HELP_MOVIE                       = 0x0017;
const ZIL_NUMBERID HELP_SEP1                        = 0x0018;
const ZIL_NUMBERID HELP_MOVIE_CATALOG               = 0x0019;
const ZIL_NUMBERID TOOL_BAR                         = 0x000B;
const ZIL_NUMBERID CREATE_BUTTON                    = 0x0012;
const ZIL_NUMBERID DELETE_BUTTON                    = 0x0014;
const ZIL_NUMBERID LOAD_BUTTON                      = 0x000D;
const ZIL_NUMBERID STORE_BUTTON                     = 0x000E;
#endif

#if defined(USE_MOVIE_INFORMATION)
const ZIL_NUMBERID INFO_PTITLE                      = 0x0004;
const ZIL_NUMBERID FLD_INFO_TITLE                   = 0x0005;
const ZIL_NUMBERID INFO_PCOPYRIGHT                  = 0x0006;
const ZIL_NUMBERID FLD_INFO_COPYRIGHT               = 0x0045;
const ZIL_NUMBERID FLD_INFO_LENGTH                  = 0x002E;
const ZIL_NUMBERID INFO_PDIRECTOR                   = 0x0007;
const ZIL_NUMBERID FLD_INFO_DIRECTOR                = 0x000D;
const ZIL_NUMBERID INFO_PACTORS                     = 0x0008;
const ZIL_NUMBERID FLD_INFO_ACTORS                  = 0x000E;
const ZIL_NUMBERID INFO_PDESCRIPTION                = 0x0009;
const ZIL_NUMBERID FLD_INFO_DESCRIPTION             = 0x0010;
const ZIL_NUMBERID INFO_SAVE                        = 0x0001;
const ZIL_NUMBERID FLD_PLENGTH                      = 0x0057;
const ZIL_NUMBERID INFO_CLOSE                       = 0x0002;
const ZIL_NUMBERID INFO_HELP                        = 0x0003;
#endif

#if defined(USE_MOVIE_SELECTION)
const ZIL_NUMBERID SELECT_PTITLE                    = 0x0001;
const ZIL_NUMBERID FLD_SELECT_TITLE                 = 0x0002;
const ZIL_NUMBERID FLD_SELECT_SELECTION             = 0x0006;
const ZIL_NUMBERID SELECT_OK                        = 0x0003;
const ZIL_NUMBERID SELECT_CANCEL                    = 0x0004;
const ZIL_NUMBERID SELECT_HELP                      = 0x0005;
#endif

#if defined(USE_DERIVED_OBJECTS)
#endif

