#if defined(USE_HELP_CONTEXTS)
const UI_HELP_CONTEXT HELP_GENERAL                     = 0x0001; // General Help
const UI_HELP_CONTEXT HELP_HELLO_UNIVERSE              = 0x0002; // Hello Universe Help
const UI_HELP_CONTEXT HELP_UNIVERSE_INFORMATION        = 0x0003; // Universe Information Help
#endif

#if defined(USE_UNIVERSE_INFORMATION_WINDOW)
const ZIL_NUMBERID FIELD_1                          = 0x0001;
const ZIL_NUMBERID FIELD_2                          = 0x0002;
const ZIL_NUMBERID FIELD_3                          = 0x0003;
const ZIL_NUMBERID FIELD_4                          = 0x0004;
const ZIL_NUMBERID FIELD_5                          = 0x0005;
const ZIL_NUMBERID FIELD_6                          = 0x0006;
const ZIL_NUMBERID FIELD_7                          = 0x0007;
const ZIL_NUMBERID FIELD_8                          = 0x0008;
const ZIL_NUMBERID FIELD_9                          = 0x0009;
#endif

#if defined(USE_HELLO_UNIVERSE_WINDOW)
const ZIL_NUMBERID FIELD_1                          = 0x0001;
#endif

#if defined(USE_DERIVED_OBJECTS)
#endif

