# DISPLAY example makefile

# ----- Usage --------------------------------------------------------------
usage: .SYMBOLIC
	@echo ...........
	@echo ...........
	@echo (This tutorial is not supported in Windows NT)
	@echo ...........
	@echo ...........

# ----- Windows NT ----------------------------------------------------------
winnt: .SYMBOLIC
	@echo (This tutorial is not supported in Windows NT)

#
