#if defined(USE_HELP_CONTEXTS)
#endif

#if defined(USE_MESSAGE_TABLE)
const ZIL_NUMBERID ZMSG_0                           = 0x0000;
const ZIL_NUMBERID ZMSG_1                           = 0x0001;
const ZIL_NUMBERID ZMSG_2                           = 0x0002;
const ZIL_NUMBERID ZMSG_3                           = 0x0003;
const ZIL_NUMBERID ZMSG_4                           = 0x0004;
const ZIL_NUMBERID ZMSG_5                           = 0x0005;
#endif

#if defined(USE_WINDOW)
const ZIL_NUMBERID TOOL_BAR                         = 0x0001;
const ZIL_NUMBERID FIELD_3                          = 0x0003;
const ZIL_NUMBERID FIELD_4                          = 0x0004;
const ZIL_NUMBERID FIELD_5                          = 0x0005;
const ZIL_NUMBERID FIELD_6                          = 0x0006;
const ZIL_NUMBERID FIELD_7                          = 0x0007;
const ZIL_NUMBERID FIELD_9                          = 0x0009;
const ZIL_NUMBERID STATUS_BAR                       = 0x000C;
const ZIL_NUMBERID STATUS_STRING                    = 0x000D;
#endif

#if defined(USE_DERIVED_OBJECTS)
#endif

