#if defined(USE_HELP_CONTEXTS)
#endif

#if defined(USE_WIN_BUTTON)
const ZIL_NUMBERID B_1                              = 0x0001;
const ZIL_NUMBERID B_2                              = 0x0002;
const ZIL_NUMBERID B_3                              = 0x0003;
const ZIL_NUMBERID B_4                              = 0x0004;
const ZIL_NUMBERID B_5                              = 0x0005;
#endif

#if defined(USE_DERIVED_OBJECTS)
#endif

